[build]
command = "npm run build" 
publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://mydevsspace.me/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200