[build]
command = "npm run build" 
publish = "dist"

[[redirects]]
  from = "/api/auth/google"
  to = "https://mydevsspace.me/auth/google"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200